unit TestUnit2;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Unit2, System.Generics.Collections;

type
  // Test methods for class TCalculadorDeDescontos

  TestTCalculadorDeDescontos = class(TTestCase)
  strict private
    FCalculadorDeDescontos: TCalculadorDeDescontos;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcular;
  end;

implementation

procedure TestTCalculadorDeDescontos.SetUp;
begin
  FCalculadorDeDescontos := TCalculadorDeDescontos.Create;
end;

procedure TestTCalculadorDeDescontos.TearDown;
begin
  // FCalculadorDeDescontos.Free;
  FCalculadorDeDescontos := nil;
end;

procedure TestTCalculadorDeDescontos.TestCalcular;
const
  DESCONTO_MENOR_500_REAIS = 5;
var
  ReturnValue: Double;
  _AOrcamento: TOrcamento;
begin
  _AOrcamento := TOrcamento.Create(100);
  _AOrcamento.AdicionarItem(TItem.Create('Cafe', 200));
  _AOrcamento.AdicionarItem(TItem.Create('Arroz', 300));
  _AOrcamento.AdicionarItem(TItem.Create('Carne', 300));
  _AOrcamento.AdicionarItem(TItem.Create('Feijão', 300));

  ReturnValue := FCalculadorDeDescontos.Calcular(_AOrcamento);

  CheckEquals(DESCONTO_MENOR_500_REAIS, ReturnValue);

end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTCalculadorDeDescontos.Suite);

end.
